version: '3.8'

services:
  fastapi_app:
    build: .
    container_name: fastapi_container
    ports:
      - "8000:8000"
    volumes:
      - ./cargo_placement.log:/app/cargo_placement.log
    environment:
      - PYTHONUNBUFFERED=1
